package net.pedroricardo;

import net.fabricmc.api.ModInitializer;

import net.fabricmc.fabric.api.networking.v1.PacketByteBufs;
import net.fabricmc.fabric.api.networking.v1.S2CPlayChannelEvents;
import net.minecraft.sound.SoundEvents;
import net.minecraft.util.Identifier;
import net.pedroricardo.content.HeadURLs;
import net.pedroricardo.content.HeadedRewrittenConfig;
import net.pedroricardo.content.TextureToServerHeadMap;
import net.pedroricardo.content.loottable.HeadedLootConditionTypes;
import net.pedroricardo.content.loottable.HeadedLootTable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class HeadedRewritten implements ModInitializer {
	public static final String MOD_ID = "headed-rewritten";
    public static final Logger LOGGER = LoggerFactory.getLogger(MOD_ID);

	@Override
	public void onInitialize() {
		HeadedLootConditionTypes.init();
		HeadedRewrittenConfig.HANDLER.load();
		if (HeadedRewrittenConfig.HANDLER.instance().chargedCreeperDrops) {
			HeadedLootTable.init();
		}
		TextureToServerHeadMap.addHead(HeadURLs.WHITE_SHEEP, "White Sheep", SoundEvents.ENTITY_SHEEP_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.ORANGE_SHEEP, "Orange Sheep", SoundEvents.ENTITY_SHEEP_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.MAGENTA_SHEEP, "Magenta Sheep", SoundEvents.ENTITY_SHEEP_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.LIGHT_BLUE_SHEEP, "Light Blue Sheep", SoundEvents.ENTITY_SHEEP_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.YELLOW_SHEEP, "Yellow Sheep", SoundEvents.ENTITY_SHEEP_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.LIME_SHEEP, "Lime Sheep", SoundEvents.ENTITY_SHEEP_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.PINK_SHEEP, "Pink Sheep", SoundEvents.ENTITY_SHEEP_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.GRAY_SHEEP, "Gray Sheep", SoundEvents.ENTITY_SHEEP_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.LIGHT_GRAY_SHEEP, "Light Gray Sheep", SoundEvents.ENTITY_SHEEP_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.CYAN_SHEEP, "Cyan Sheep", SoundEvents.ENTITY_SHEEP_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.PURPLE_SHEEP, "Purple Sheep", SoundEvents.ENTITY_SHEEP_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.BLUE_SHEEP, "Blue Sheep", SoundEvents.ENTITY_SHEEP_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.BROWN_SHEEP, "Brown Sheep", SoundEvents.ENTITY_SHEEP_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.GREEN_SHEEP, "Green Sheep", SoundEvents.ENTITY_SHEEP_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.RED_SHEEP, "Red Sheep", SoundEvents.ENTITY_SHEEP_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.BLACK_SHEEP, "Black Sheep", SoundEvents.ENTITY_SHEEP_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.JEB_SHEEP, "jeb_ Sheep", SoundEvents.ENTITY_SHEEP_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.ALLAY, "Allay", SoundEvents.ENTITY_ALLAY_AMBIENT_WITHOUT_ITEM.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.LUCY_AXOLOTL, "Lucy Axolotl", SoundEvents.ENTITY_AXOLOTL_IDLE_AIR.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.WILD_AXOLOTL, "Wild Axolotl", SoundEvents.ENTITY_AXOLOTL_IDLE_AIR.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.GOLD_AXOLOTL, "Gold Axolotl", SoundEvents.ENTITY_AXOLOTL_IDLE_AIR.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.CYAN_AXOLOTL, "Cyan Axolotl", SoundEvents.ENTITY_AXOLOTL_IDLE_AIR.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.BLUE_AXOLOTL, "Blue Axolotl", SoundEvents.ENTITY_AXOLOTL_IDLE_AIR.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.BAT, "Bat", SoundEvents.ENTITY_BAT_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.BEE, "Bee", SoundEvents.ENTITY_BEE_LOOP.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.POLLINATED_BEE, "Pollinated Bee", SoundEvents.ENTITY_BEE_POLLINATE.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.ANGRY_BEE, "Angry Bee", SoundEvents.ENTITY_BEE_LOOP_AGGRESSIVE.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.ANGRY_POLLINATED_BEE, "Angry Pollinated Bee", SoundEvents.ENTITY_BEE_LOOP_AGGRESSIVE.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.BLAZE, "Blaze", SoundEvents.ENTITY_BLAZE_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.CAMEL, "Camel", SoundEvents.ENTITY_CAMEL_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.ALL_BLACK_CAT, "Black Cat", SoundEvents.ENTITY_CAT_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.BLACK_CAT, "Tuxedo Cat", SoundEvents.ENTITY_CAT_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.BRITISH_SHORTHAIR_CAT, "British Shorthair", SoundEvents.ENTITY_CAT_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.CALICO_CAT, "Calico Cat", SoundEvents.ENTITY_CAT_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.JELLIE_CAT, "Jellie Cat", SoundEvents.ENTITY_CAT_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.PERSIAN_CAT, "Persian Cat", SoundEvents.ENTITY_CAT_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.RAGDOLL_CAT, "Ragdoll Cat", SoundEvents.ENTITY_CAT_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.RED_CAT, "Red Cat", SoundEvents.ENTITY_CAT_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.SIAMESE_CAT, "Siamese Cat", SoundEvents.ENTITY_CAT_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.TABBY_CAT, "Tabby Cat", SoundEvents.ENTITY_CAT_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.WHITE_CAT, "White Cat", SoundEvents.ENTITY_CAT_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.CAVE_SPIDER, "Cave Spider", SoundEvents.ENTITY_SPIDER_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.CHICKEN, "Chicken", SoundEvents.ENTITY_CHICKEN_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.COD, "Cod", SoundEvents.ENTITY_COD_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.COW, "Cow", SoundEvents.ENTITY_COW_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.CREPEER2159, "Armor Stand", SoundEvents.ENTITY_GENERIC_EXPLODE.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.DOLPHIN, "Dolphin", SoundEvents.ENTITY_DOLPHIN_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.DONKEY, "Donkey", SoundEvents.ENTITY_DONKEY_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.DROWNED, "Drowned", SoundEvents.ENTITY_DROWNED_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.ELDER_GUARDIAN, "Elder Guardian", SoundEvents.ENTITY_ELDER_GUARDIAN_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.ENDERMAN, "Enderman", SoundEvents.ENTITY_ENDERMAN_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.ENDERMITE, "Endermite", SoundEvents.ENTITY_ENDERMITE_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.EVOKER, "Evoker", SoundEvents.ENTITY_EVOKER_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.FOX, "Fox", SoundEvents.ENTITY_FOX_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.SNOW_FOX, "Snow Fox", SoundEvents.ENTITY_FOX_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.COLD_FROG, "Cold Frog", SoundEvents.ENTITY_FROG_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.TEMPERATE_FROG, "Temperate Frog", SoundEvents.ENTITY_FROG_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.WARM_FROG, "Warm Frog", SoundEvents.ENTITY_FROG_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.GHAST, "Ghast", SoundEvents.ENTITY_GHAST_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.GLOW_SQUID, "Glow Squid", SoundEvents.ENTITY_GLOW_SQUID_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.GOAT, "Goat", SoundEvents.ENTITY_GOAT_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.GUARDIAN, "Guardian", SoundEvents.ENTITY_GUARDIAN_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.HOGLIN, "Hoglin", SoundEvents.ENTITY_HOGLIN_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.WHITE_HORSE, "White Horse", SoundEvents.ENTITY_HORSE_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.CREAMY_HORSE, "Creamy Horse", SoundEvents.ENTITY_HORSE_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.CHESTNUT_HORSE, "Chestnut Horse", SoundEvents.ENTITY_HORSE_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.BROWN_HORSE, "Brown Horse", SoundEvents.ENTITY_HORSE_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.BLACK_HORSE, "Black Horse", SoundEvents.ENTITY_HORSE_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.GRAY_HORSE, "Gray Horse", SoundEvents.ENTITY_HORSE_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.DARK_BROWN_HORSE, "Dark Brown Horse", SoundEvents.ENTITY_HORSE_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.HUSK, "Husk", SoundEvents.ENTITY_HUSK_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.ILLUSIONER, "Illusioner", SoundEvents.ENTITY_ILLUSIONER_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.IRON_GOLEM, "Iron Golem", SoundEvents.ENTITY_IRON_GOLEM_STEP.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.CREAMY_LLAMA, "Creamy Llama", SoundEvents.ENTITY_LLAMA_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.WHITE_LLAMA, "White Llama", SoundEvents.ENTITY_LLAMA_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.BROWN_LLAMA, "Brown Llama", SoundEvents.ENTITY_LLAMA_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.GRAY_LLAMA, "Gray Llama", SoundEvents.ENTITY_LLAMA_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.MAGMA_CUBE, "Magma Cube", SoundEvents.ENTITY_MAGMA_CUBE_JUMP.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.RED_MOOSHROOM, "Red Mooshroom", SoundEvents.ENTITY_COW_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.BROWN_MOOSHROOM, "Brown Mooshroom", SoundEvents.ENTITY_COW_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.MULE, "Mule", SoundEvents.ENTITY_MULE_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.OCELOT, "Ocelot", SoundEvents.ENTITY_OCELOT_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.AGGRESSIVE_PANDA, "Aggressive Panda", SoundEvents.ENTITY_PANDA_AGGRESSIVE_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.BROWN_PANDA, "Brown Panda", SoundEvents.ENTITY_PANDA_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.LAZY_PANDA, "Lazy Panda", SoundEvents.ENTITY_PANDA_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.PANDA, "Panda", SoundEvents.ENTITY_PANDA_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.PLAYFUL_PANDA, "Playful Panda", SoundEvents.ENTITY_PANDA_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.WEAK_PANDA, "Weak Panda", SoundEvents.ENTITY_PANDA_SNEEZE.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.WORRIED_PANDA, "Worried Panda", SoundEvents.ENTITY_PANDA_WORRIED_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.BLUE_PARROT, "Blue Parrot", SoundEvents.ENTITY_PARROT_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.GREEN_PARROT, "Green Parrot", SoundEvents.ENTITY_PARROT_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.GRAY_PARROT, "Gray Parrot", SoundEvents.ENTITY_PARROT_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.RED_PARROT, "Red Parrot", SoundEvents.ENTITY_PARROT_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.CYAN_PARROT, "Cyan Parrot", SoundEvents.ENTITY_PARROT_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.PHANTOM, "Phantom", SoundEvents.ENTITY_PHANTOM_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.PIG, "Pig", SoundEvents.ENTITY_PIG_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.PIGLIN_BRUTE, "Piglin Brute", SoundEvents.ENTITY_PIGLIN_BRUTE_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.PILLAGER, "Pillager", SoundEvents.ENTITY_PILLAGER_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.POLAR_BEAR, "Polar Bear", SoundEvents.ENTITY_POLAR_BEAR_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.PUFFERFISH, "Pufferfish", SoundEvents.ENTITY_PUFFER_FISH_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.BLACK_RABBIT, "Black Rabbit", SoundEvents.ENTITY_RABBIT_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.BROWN_RABBIT, "Brown Rabbit", SoundEvents.ENTITY_RABBIT_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.KILLER_BUNNY, "The Killer Bunny", SoundEvents.ENTITY_RABBIT_ATTACK.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.GOLD_RABBIT, "Gold Rabbit", SoundEvents.ENTITY_RABBIT_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.SALT_PEPPER_RABBIT, "Salt and Pepper Rabbit", SoundEvents.ENTITY_RABBIT_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.TOAST_RABBIT, "Toast", SoundEvents.ENTITY_RABBIT_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.WHITE_RABBIT, "White Rabbit", SoundEvents.ENTITY_RABBIT_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.BLACK_WHITE_RABBIT, "Black and White Rabbit", SoundEvents.ENTITY_RABBIT_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.RAVAGER, "Ravager", SoundEvents.ENTITY_RAVAGER_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.SALMON, "Salmon", SoundEvents.ENTITY_SALMON_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.SHULKER, "Shulker", SoundEvents.ENTITY_SHULKER_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.SILVERFISH, "Silverfish", SoundEvents.ENTITY_SILVERFISH_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.SKELETON_HORSE, "Skeleton Horse", SoundEvents.ENTITY_SKELETON_HORSE_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.SLIME, "Slime", SoundEvents.ENTITY_SLIME_JUMP.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.SNIFFER, "Sniffer", SoundEvents.ENTITY_SNIFFER_SNIFFING.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.SNOW_GOLEM, "Snow Golem", SoundEvents.ENTITY_SNOW_GOLEM_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.SPIDER, "Spider", SoundEvents.ENTITY_SPIDER_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.SQUID, "Squid", SoundEvents.ENTITY_SQUID_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.STRAY, "Stray", SoundEvents.ENTITY_STRAY_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.STRIDER, "Strider", SoundEvents.ENTITY_STRIDER_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.TADPOLE, "Tadpole", SoundEvents.ENTITY_TADPOLE_FLOP.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.CREAMY_TRADER_LLAMA, "Creamy Trader Llama", SoundEvents.ENTITY_LLAMA_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.WHITE_TRADER_LLAMA, "White Trader Llama", SoundEvents.ENTITY_LLAMA_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.BROWN_TRADER_LLAMA, "Brown Trader Llama", SoundEvents.ENTITY_LLAMA_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.GRAY_TRADER_LLAMA, "Gray Trader Llama", SoundEvents.ENTITY_LLAMA_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.TROPICAL_FISH, "Tropical Fish", SoundEvents.ENTITY_TROPICAL_FISH_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.TURTLE, "Turtle", SoundEvents.ENTITY_TURTLE_AMBIENT_LAND.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.VEX, "Vex", SoundEvents.ENTITY_VEX_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.CHARGING_VEX, "Charging Vex", SoundEvents.ENTITY_VEX_CHARGE.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.VILLAGER, "Villager", SoundEvents.ENTITY_VILLAGER_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.ARMORER_VILLAGER, "Armorer Villager", SoundEvents.ENTITY_VILLAGER_WORK_ARMORER.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.BUTCHER_VILLAGER, "Butcher Villager", SoundEvents.ENTITY_VILLAGER_WORK_BUTCHER.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.CARTOGRAPHER_VILLAGER, "Cartographer Villager", SoundEvents.ENTITY_VILLAGER_WORK_CARTOGRAPHER.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.CLERIC_VILLAGER, "Cleric Villager", SoundEvents.ENTITY_VILLAGER_WORK_CLERIC.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.FARMER_VILLAGER, "Farmer Villager", SoundEvents.ENTITY_VILLAGER_WORK_FARMER.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.FISHERMAN_VILLAGER, "Fisherman Villager", SoundEvents.ENTITY_VILLAGER_WORK_FISHERMAN.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.FLETCHER_VILLAGER, "Fletcher Villager", SoundEvents.ENTITY_VILLAGER_WORK_FLETCHER.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.LIBRARIAN_VILLAGER, "Librarian Villager", SoundEvents.ENTITY_VILLAGER_WORK_LIBRARIAN.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.VINDICATOR, "Vindicator", SoundEvents.ENTITY_VINDICATOR_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.WANDERING_TRADER, "Wandering Trader", SoundEvents.ENTITY_WANDERING_TRADER_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.WARDEN, "Warden", SoundEvents.ENTITY_WARDEN_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.WITCH, "Witch", SoundEvents.ENTITY_WITCH_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.WITHER, "Wither", SoundEvents.ENTITY_WITHER_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.WITHER_PROJECTILE, "Wither Projectile", SoundEvents.ENTITY_WITHER_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.BLUE_WITHER_PROJECTILE, "Blue Wither Projectile", SoundEvents.ENTITY_WITHER_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.WOLF, "Wolf", SoundEvents.ENTITY_WOLF_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.ANGRY_WOLF, "Angry Wolf", SoundEvents.ENTITY_WOLF_GROWL.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.ZOGLIN, "Zoglin", SoundEvents.ENTITY_ZOGLIN_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.ZOMBIE_HORSE, "Zombie Horse", SoundEvents.ENTITY_ZOMBIE_HORSE_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.ZOMBIE_VILLAGER, "Zombie Villager", SoundEvents.ENTITY_ZOMBIE_VILLAGER_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.ARMORER_ZOMBIE_VILLAGER, "Armorer Zombie Villager", SoundEvents.ENTITY_ZOMBIE_VILLAGER_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.BUTCHER_ZOMBIE_VILLAGER, "Butcher Zombie Villager", SoundEvents.ENTITY_ZOMBIE_VILLAGER_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.CARTOGRAPHER_ZOMBIE_VILLAGER, "Cartographer Zombie Villager", SoundEvents.ENTITY_ZOMBIE_VILLAGER_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.CLERIC_ZOMBIE_VILLAGER, "Cleric Zombie Villager", SoundEvents.ENTITY_ZOMBIE_VILLAGER_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.FARMER_ZOMBIE_VILLAGER, "Farmer Zombie Villager", SoundEvents.ENTITY_ZOMBIE_VILLAGER_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.FISHERMAN_ZOMBIE_VILLAGER, "Fisherman Zombie Villager", SoundEvents.ENTITY_ZOMBIE_VILLAGER_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.FLETCHER_ZOMBIE_VILLAGER, "Fletcher Zombie Villager", SoundEvents.ENTITY_ZOMBIE_VILLAGER_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.LIBRARIAN_ZOMBIE_VILLAGER, "Librarian Zombie Villager", SoundEvents.ENTITY_ZOMBIE_VILLAGER_AMBIENT.getId().toString());
		TextureToServerHeadMap.addHead(HeadURLs.ZOMBIFIED_PIGLIN, "Zombified Piglin", SoundEvents.ENTITY_ZOMBIFIED_PIGLIN_AMBIENT.getId().toString());

		S2CPlayChannelEvents.REGISTER.register(new Identifier(MOD_ID, MOD_ID), (handler, sender, server, channels) ->
			sender.sendPacket(new Identifier(MOD_ID, MOD_ID), PacketByteBufs.empty())
		);
		LOGGER.info("Initializing Headed Rewritten");
	}
}